### ISSUE TITLE
Short info on orthography profile

### ISSUE THREAD

**Issue by LinguList** [lexibank/abvd_oceanic#1]
I assume the profile to be rather tough, but I think it can be done. The context profile has some 1600 lines, but no decisions look really tough to me.

It might be helpful to consult with the specialists on individual symbols. E.g., I don't know what the `|` means, which occurs in many words, like `'sai|a`. 

And it is not clear if accents on sounds are rather due to tonal differences, or if they denote something else.

**Comment by maryewal** [comment]
This might be marking [a] as a separate morpheme, but could also be tone...what is the language?

As for accents, it depends on the region and the linguistic tradition. French linguists in the Pacific often marked glottal stops on the following vowel, and sometimes marked long vowels using accents too.

**Comment by SimonGreenhill** [comment]
I'm pretty sure these are morpheme boundaries. This is "to sew" in Mengen, the SIL dictionary has this:

```
sai  v.  sew,  weave.  Vtr:  saia;  Vdur:  saisai;  Vph:  sainga
```

(so the `|a` in this language marks Vtr).

**Comment by LinguList** [comment]
Okay, we will go with this, thanks!

**Comment by LinguList** [comment]
I treat most diacritic vowels now by using the normal vowel and marking this with a slash, like `á/a`. So when looking at individual languages later, you can see that this is originally something else, but all algorithms will treat it as an `a`. This way of representing the data is not optimal, but helps a bit in looking at the things that happen there.
